### ISSUE TITLE
OpenFOAM environment not defined correctly

### ISSUE THREAD

**Issue by MakisH** [kunstrasenspringer/precice_st#1]
Dear @kunstrasenspringer,

Trying to debug your problem mentioned in https://github.com/precice/tutorials/issues/3, I noticed that defining the OpenFOAM environment inside a Docker container is not as trivial as in a normal installation.

First of all, keep in mind that every Docker step creates a new intermediate container, which is then deleted, together with its local environment. Therefore, sourcing the `/opt/openfoam-dev/etc/bashrc` file inside a dedicated `RUN` command is actually not changing anything. That's why you need to source it every time before running any OpenFOAM command.

Moreover, I noticed that even in this case, some paths, such as the `FOAM_RUN` are not set correctly, because the `USER` variable is not defined in this minimal environment. You can check the environment using `env`. One approach could be to use `ENV USER=alice` to add this manually in the environment, however there are probably better solutions for this. Maybe you can just invoke `docker run` in a better way to solve this.

On Dockerhub you can find many Dockerfiles for OpenFOAM, you may find a better approach there.

Here is a minimum working example, based on your `Dockerfile.of-ccx`:

```
FROM kunstrasenspringer/precice:latest

USER root
RUN apt-get update && apt-get install -y \
    software-properties-common \
    wget \
    apt-transport-https \
    libyaml-cpp-dev \
    bzip2 \
    libbz2-dev \
    cmake \
    automake \
    autoconf \
    autotools-dev \
    libarpack2-dev

# Install openfoam
RUN add-apt-repository "http://dl.openfoam.org/ubuntu dev"
RUN sh -c "wget -O - http://dl.openfoam.org/gpg.key | apt-key add -"
RUN add-apt-repository http://dl.openfoam.org/ubuntu && apt update
RUN apt-get -y install openfoam-dev --no-install-recommends

RUN rm /bin/sh && ln -s /bin/bash /bin/sh

USER alice
WORKDIR /home/alice

RUN source /opt/openfoam-dev/etc/bashrc

ENV USER=alice
ENTRYPOINT source /opt/openfoam-dev/etc/bashrc && env
```

Also, please check if  wmake creates the `FOAM_USER_LIBBIN` if it does not already exist. If not, please open an issue on the OpenFOAM adapter and I will improve this later.

Good luck!

(by the way, I am not sure why you overwrite the shell binary, you may want to check this again)

**Comment by kunstrasenspringer** [comment]
Hi @MakisH ,
thank you for your input. Like you already explained, a single layer in a docker image does not inherit the environmental variables of previous layers. Since I only need OpenFOAM commands two times -while building the adapter and while simulating-, I "manually" source  `/opt/openfoam-dev/etc/bashrc` right before I need the OpenFOAM commands.
Also thank you for the tip to set `USER=alice`. I missed that.
Also there is no need to overwrite the shell binary, I took that from an another example.

I'm closing this, but feel free to add more to the issue.

Best regards,
kunstrasenspringer.
